version: "3.9"
services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: db
            POSTGRES_USER: username
            POSTGRES_PASSWORD: password
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - '5432'
        networks:
            - back
        # Está todo bien con la base de datos?
        healthcheck:
            test: pg_isready -U username -d db
            interval: 1s
            timeout: 5s
            retries: 10

    server:
        image: dogia/api:latest
        environment: 
            DB_NAME: db
            DB_USER: username
            DB_PASSWORD: password
        volumes:
            - ./api:/usr/src/app
        # Dependemos de la base de datos y esperamos hasta que esté activa
        depends_on:
            db:
                condition: service_healthy
        command: "./start.sh"
        ports:
            - '81:8000'
        networks:
            - back
    app:
        image: dogia/app:latest
        volumes:
            - ./app:/usr/src/app
        ports:
            - '80:80'
        environment:
            - NGINX_PORT=80

networks:
    back:
        driver: bridge
        attachable: true
